# Generated by Django 5.2 on 2025-05-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='babosas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBabosa', models.CharField(max_length=10, unique=True, verbose_name='Codigo Babosa')),
                ('NombreBabosa', models.CharField(max_length=10, unique=True, verbose_name='Codigo Babosa')),
                ('tipoBabosa', models.CharField(choices=[('1', 'Malvadas'), ('2', 'Elementales'), ('3', 'Megamorficas'), ('4', 'Guardianas'), ('5', 'Extra')], max_length=1, verbose_name='Tipo Babosa')),
                ('elementoBabosa', models.CharField(choices=[('1', 'Aire'), ('2', 'Tierra'), ('3', 'Fuego'), ('4', 'Energia'), ('5', 'Agua')], max_length=1, verbose_name='Elemento Babosa')),
            ],
        ),
    ]
