# Generated by Django 5.2 on 2025-05-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babosas',
            name='NombreBabosa',
            field=models.CharField(max_length=10, unique=True, verbose_name='Nombre Babosa'),
        ),
    ]
