# Generated by Django 5.2 on 2025-05-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosas', '0002_alter_babosas_nombrebabosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='babosas',
            name='Protoforma',
            field=models.ImageField(blank=True, null=True, upload_to='babosas_images/protoforma'),
        ),
        migrations.AddField(
            model_name='babosas',
            name='Transformacion',
            field=models.ImageField(blank=True, null=True, upload_to='babosas_images/transformacion'),
        ),
    ]
