# Generated by Django 5.2 on 2025-05-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosas', '0003_babosas_protoforma_babosas_transformacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babosas',
            name='NombreBabosa',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre Babosa'),
        ),
        migrations.AlterField(
            model_name='babosas',
            name='Protoforma',
            field=models.ImageField(blank=True, null=True, upload_to='protoforma'),
        ),
        migrations.AlterField(
            model_name='babosas',
            name='Transformacion',
            field=models.ImageField(blank=True, null=True, upload_to='transformacion'),
        ),
    ]
