# Generated by Django 5.2 on 2025-05-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babosas', '0004_alter_babosas_nombrebabosa_alter_babosas_protoforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babosas',
            name='elementoBabosa',
            field=models.CharField(choices=[('1', 'Aire'), ('2', 'Tierra'), ('3', 'Fuego'), ('4', 'Energia'), ('5', 'Agua'), ('6', 'Desconocido')], max_length=1, verbose_name='Elemento Babosa'),
        ),
    ]
